// Generated by gencpp from file harris_chase_object/DistanceAngle.msg
// DO NOT EDIT!


#ifndef HARRIS_CHASE_OBJECT_MESSAGE_DISTANCEANGLE_H
#define HARRIS_CHASE_OBJECT_MESSAGE_DISTANCEANGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace harris_chase_object
{
template <class ContainerAllocator>
struct DistanceAngle_
{
  typedef DistanceAngle_<ContainerAllocator> Type;

  DistanceAngle_()
    : distance(0.0)
    , angle(0.0)  {
    }
  DistanceAngle_(const ContainerAllocator& _alloc)
    : distance(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef float _distance_type;
  _distance_type distance;

   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::harris_chase_object::DistanceAngle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::harris_chase_object::DistanceAngle_<ContainerAllocator> const> ConstPtr;

}; // struct DistanceAngle_

typedef ::harris_chase_object::DistanceAngle_<std::allocator<void> > DistanceAngle;

typedef boost::shared_ptr< ::harris_chase_object::DistanceAngle > DistanceAnglePtr;
typedef boost::shared_ptr< ::harris_chase_object::DistanceAngle const> DistanceAngleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::harris_chase_object::DistanceAngle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::harris_chase_object::DistanceAngle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace harris_chase_object

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'harris_chase_object': ['/home/charris/introrobotics/turtlebot-gt-2018/src/harris_chase_object/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::harris_chase_object::DistanceAngle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::harris_chase_object::DistanceAngle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::harris_chase_object::DistanceAngle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::harris_chase_object::DistanceAngle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::harris_chase_object::DistanceAngle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::harris_chase_object::DistanceAngle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::harris_chase_object::DistanceAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4933fd9ad08c4f2a5e0f3f6e555256ee";
  }

  static const char* value(const ::harris_chase_object::DistanceAngle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4933fd9ad08c4f2aULL;
  static const uint64_t static_value2 = 0x5e0f3f6e555256eeULL;
};

template<class ContainerAllocator>
struct DataType< ::harris_chase_object::DistanceAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "harris_chase_object/DistanceAngle";
  }

  static const char* value(const ::harris_chase_object::DistanceAngle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::harris_chase_object::DistanceAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 distance\n\
float64 angle\n\
";
  }

  static const char* value(const ::harris_chase_object::DistanceAngle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::harris_chase_object::DistanceAngle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DistanceAngle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::harris_chase_object::DistanceAngle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::harris_chase_object::DistanceAngle_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HARRIS_CHASE_OBJECT_MESSAGE_DISTANCEANGLE_H
